package me.pluto.nilinproject.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "admin")
@Data
public class Admin{

    @Id
    private String id;

    private String user;
    private String password;

    public Admin(String user, String password) {
        this.user = user;
        this.password = password;
    }

    //Setters and getters are generated by lombok
}
