package me.pluto.nilinproject.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.ArrayList;
import java.util.List;

@Document
@Data
public class Course {

    @Id
    private String id;

    private String teacherName;
    private int capacity;
    private String location;
    private List<Long> attendees;

    public Course(int capacity, String location){
        this.capacity = capacity;
        this.location = location;
        this.attendees = new ArrayList<>();
    }

    //Setters and getters are generated by lombok

}
