package me.pluto.nilinproject.model;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.ArrayList;
import java.util.List;

@Document(collection = "teacher")
@Data
public class Teacher{

    @Id
    private String id;

    private String name;
    private List<String> coursesId = new ArrayList<>();

    //Setters and getters are generated by lombok
}
